password = "$2$tu3wg8twpfw1tbkhr7cu73bwmhsbrdkj$szkcmxgxrrnxwgedpwf85b3o8pscd83ainq5s6bmjre75r6yma4b"

keypair {
    algorithm = "curve25519";
    pubkey = "h466r47dpt4nmrk7kdw5xza5fy31gb6t1qz441gcrcu64xj3mmqy";
    privkey = "aysgzz3m7bmumfd81qwoq3rkyrghjdxi3ik5jjs35a7ankgqfy1y";
    type = "kex";
    encoding = "base32";
    id = "h58sr8wcim1qwd5fiftywtd7sbzw5ieriy8i5d8y6rwkuuk6w8m14emasmfk3bibkwb5n7yyd9z6wcporh7d49ikpnxs8tx5pnp6m4d";
}
